draw_set_font(MainFont)
draw_text(5, 0, "Controls:")
draw_text(5, 60, "A / left arrow / dpad left - Move Left")
draw_text(5, 120, "D / right arrow / dpad right - Move Right")
draw_text(5, 180, "W / up arrow / space / dpad up / A - Jump")
draw_text(5, 240, "S / down arrow / dpad down - Dive")
draw_text(5, 300, "R / start - Restart")
draw_text(5, 360, "Tab / select - Show Map")